#pragma once
#include "gfx/gfx.h"
#include "gfx/shader.h"
#include "gfx/vertex.h"
#include "gfx/vertex_array.h"
#include "gfx/buffer.h"
#include "gfx/texture.h"
#include "gfx/context.h"
#include <stb_image.h>